"""Explicit Task38 public input schema metadata.

This module deliberately contains no TOML loader, validator, resolver, or
runner adapter.  The whitelist is written out here so dataclass and argparse
fields cannot silently become public input keys during T1.
"""

from dataclasses import dataclass
from types import MappingProxyType
from typing import Final

SCHEMA_VERSION: Final = 1
IDENTITY_KEYS: Final = (
    "schema_version",
    "model_id",
    "run_id",
    "comparison_group",
    "dimension",
)
SECTION_NAMES: Final = (
    "geometry",
    "materials",
    "incidence",
    "discretization",
    "boundary",
    "method",
    "solver",
    "execution",
    "output",
)
METHOD_KINDS: Final = (
    "2d_scattered",
    "2d_port",
    "full3d_direct",
    "full3d_iterative",
    "hybrid_direct",
    "hybrid_iterative",
)


@dataclass(frozen=True)
class FieldSpec:
    """Human- and machine-readable metadata for one public field."""

    key: str
    value_type: str
    unit: str
    required: bool
    default: str | None
    allowed: tuple[str, ...]
    applicability: tuple[str, ...]
    meaning: str
    internal_target: str
    constraints: tuple[str, ...]
    example: str


def _f(
    key: str,
    value_type: str,
    unit: str,
    applicability: tuple[str, ...],
    meaning: str,
    internal_target: str,
    example: str,
    *,
    required: bool = False,
    default: str | None = None,
    allowed: tuple[str, ...] = (),
    constraints: tuple[str, ...] = (),
) -> FieldSpec:
    """Construct one explicit whitelist entry; no fields are discovered."""

    return FieldSpec(
        key=key,
        value_type=value_type,
        unit=unit,
        required=required,
        default=default,
        allowed=allowed,
        applicability=applicability,
        meaning=meaning,
        internal_target=internal_target,
        constraints=constraints,
        example=example,
    )


_ANY_2D_3D: Final = ("2d", "3d")
_ALL_METHODS: Final = (
    "2d_scattered",
    "2d_port",
    "full3d_direct",
    "full3d_iterative",
    "hybrid_direct",
    "hybrid_iterative",
)
_HYBRID_METHODS: Final = ("hybrid_direct", "hybrid_iterative")

IDENTITY_FIELD_SPECS: Final = (
    _f(
        "schema_version",
        "integer",
        "version",
        ("all",),
        "输入合同版本",
        "schema_version",
        "1",
        required=True,
        allowed=("1",),
    ),
    _f(
        "model_id",
        "string",
        "none",
        ("all",),
        "模型/案例标识",
        "model_id",
        '"task038_example"',
        required=True,
        constraints=("safe filename characters [A-Za-z0-9_.-]+",),
    ),
    _f(
        "run_id",
        "string",
        "none",
        ("all",),
        "单次运行标识",
        "run_id",
        '"example_run_001"',
        required=True,
        constraints=(
            "safe filename characters [A-Za-z0-9_.-]+; must not overwrite an existing result",
        ),
    ),
    _f(
        "comparison_group",
        "string",
        "none",
        ("all",),
        "可比较运行的分组标识",
        "comparison_group",
        '"task038_examples"',
        required=True,
        constraints=("safe filename characters [A-Za-z0-9_.-]+",),
    ),
    _f(
        "dimension",
        "integer",
        "none",
        ("all",),
        "问题维数",
        "dimension",
        "3",
        required=True,
        allowed=("2", "3"),
    ),
)

FIELD_SPECS: Final = (
    # geometry
    _f(
        "geometry.geometry_kind",
        "string",
        "none",
        _ANY_2D_3D,
        "形状模型名称",
        "geometry_kind",
        '"rectangular_block_grating"',
        required=True,
        allowed=(
            "euv_grating_2d",
            "layered_2d",
            "airbox",
            "fresnel_interface",
            "flat_layer",
            "rectangular_block_grating",
        ),
        constraints=(
            "2D uses euv_grating_2d/layered_2d; 3D uses airbox/fresnel_interface/"
            "flat_layer/rectangular_block_grating",
        ),
    ),
    _f(
        "geometry.period_x_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "x 方向周期",
        "period_x",
        "50.0",
        required=True,
        constraints=("> 0",),
    ),
    _f(
        "geometry.period_y_nm",
        "float",
        "nm",
        ("3d",),
        "y 方向周期",
        "period_y",
        "25.0",
        required=True,
        constraints=("> 0",),
    ),
    _f(
        "geometry.z_min_nm",
        "float",
        "nm",
        ("3d",),
        "三维计算域下界",
        "z_min",
        "-10.0",
        required=True,
        constraints=("< z_max_nm",),
    ),
    _f(
        "geometry.z_max_nm",
        "float",
        "nm",
        ("3d",),
        "三维计算域上界",
        "z_max",
        "130.0",
        required=True,
        constraints=("> z_min_nm",),
    ),
    _f(
        "geometry.interface_z_nm",
        "float",
        "nm",
        ("3d",),
        "空气与基底接口 z 坐标",
        "interface_z",
        "0.0",
        required=True,
        constraints=("z_min_nm < value < z_max_nm",),
    ),
    _f(
        "geometry.air_height_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "接口上方空气厚度",
        "air_height",
        "130.0",
        required=True,
        constraints=("> 0",),
    ),
    _f(
        "geometry.substrate_thickness_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "接口下方基底厚度",
        "substrate_thickness",
        "10.0",
        required=True,
        constraints=(">= 0",),
    ),
    _f(
        "geometry.grating_width_x_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "grating x 方向宽度",
        "2D grating_width / 3D grating_width_x",
        "17.0",
        constraints=(
            ">= 0; required only for grating geometry; optional or 0 for "
            "non-grating geometry",
        ),
    ),
    _f(
        "geometry.grating_width_y_nm",
        "float",
        "nm",
        ("3d",),
        "grating y 方向宽度",
        "grating_width_y",
        "25.0",
        constraints=(
            ">= 0; required only for 3D grating geometry; optional or 0 otherwise",
        ),
    ),
    _f(
        "geometry.grating_height_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "grating 高度",
        "grating_height",
        "120.0",
        constraints=(
            ">= 0; required only for grating geometry; optional or 0 for "
            "non-grating geometry",
        ),
    ),
    # materials
    _f(
        "materials.n_air",
        "complex_pair",
        "relative index",
        _ANY_2D_3D,
        "空气复折射率 [实部, 虚部]",
        "n_air",
        "[1.0, 0.0]",
        required=True,
    ),
    _f(
        "materials.mu_r",
        "complex_pair",
        "relative permeability",
        _ANY_2D_3D,
        "相对磁导率 [实部, 虚部]",
        "mu_r",
        "[1.0, 0.0]",
        default="[1.0, 0.0]",
    ),
    _f(
        "materials.substrate_name",
        "string",
        "none",
        _ANY_2D_3D,
        "基底材料名称",
        "substrate_material_label",
        '"Si / silicon"',
        constraints=("optional descriptive label",),
    ),
    _f(
        "materials.n_substrate",
        "complex_pair",
        "relative index",
        _ANY_2D_3D,
        "基底复折射率",
        "n_substrate",
        "[0.999002304859, 0.00182649365]",
        required=False,
    ),
    _f(
        "materials.grating_name",
        "string",
        "none",
        _ANY_2D_3D,
        "grating 材料名称",
        "grating_material_label",
        '"Si / silicon"',
        constraints=("optional descriptive label",),
    ),
    _f(
        "materials.n_grating",
        "complex_pair",
        "relative index",
        _ANY_2D_3D,
        "grating 复折射率 [实部, 虚部]",
        "n_grating",
        "[0.999002304859, 0.00182649365]",
        required=False,
    ),
    # incidence
    _f(
        "incidence.wavelength_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "真空波长",
        "lambda0",
        "13.5",
        required=True,
        constraints=("> 0",),
    ),
    _f(
        "incidence.grazing_angle_deg",
        "float",
        "degree",
        ("3d",),
        "相对表面的掠射角",
        "incident_theta_deg = 90 - grazing_angle_deg",
        "1.0",
        constraints=(
            "required for Stage4 grating; 0 < value <= 90; mutually exclusive "
            "with tilt_from_downward_z_deg",
        ),
    ),
    _f(
        "incidence.tilt_from_downward_z_deg",
        "float",
        "degree",
        ("3d",),
        "Stage1/airbox/Fresnel 使用的、相对向下 z 轴的倾角",
        "incident_theta_deg",
        "10.0",
        constraints=(
            "finite; use for Stage1/Stage2 airbox/Fresnel, mutually exclusive "
            "with grazing_angle_deg",
        ),
    ),
    _f(
        "incidence.azimuth_deg",
        "float",
        "degree",
        ("3d",),
        "入射方位角",
        "incident_phi_deg",
        "0.0",
        required=True,
        constraints=("finite; method-specific range",),
    ),
    _f(
        "incidence.tilt_from_downward_y_deg",
        "float",
        "degree",
        ("2d",),
        "二维相对向下 y 轴的显式倾角；代码使用 kx=sin(theta), ky=-cos(theta)",
        "incident_angle_deg",
        "0.0",
        required=True,
        constraints=("finite; 2D convention only",),
    ),
    _f(
        "incidence.polarization",
        "enum",
        "none",
        _ANY_2D_3D,
        "偏振类型",
        "polarization_kind / polarization_type",
        '"s"',
        required=True,
        allowed=("tm", "te", "s", "p", "custom"),
        constraints=("2D allows tm/te; 3D allows s/p/custom",),
    ),
    _f(
        "incidence.custom_polarization",
        "complex_vector3",
        "none",
        ("3d",),
        "custom 复偏振向量",
        "custom_polarization",
        "[[1.0, 0.0], [0.0, 0.0], [0.0, 0.0]]",
        constraints=("3D only; required exactly when polarization=custom",),
    ),
    _f(
        "incidence.electric_amplitude",
        "float",
        "V/m relative",
        _ANY_2D_3D,
        "入射电场幅值",
        "incident_amplitude / incident_e0_v_per_m",
        "1.0",
        default="1.0",
        constraints=(">= 0",),
    ),
    # discretization
    _f(
        "discretization.nedelec_degree",
        "integer",
        "order",
        _ANY_2D_3D,
        "Nedelec 有限元阶次",
        "nedelec_degree",
        "6",
        required=True,
        constraints=(">= 1",),
    ),
    _f(
        "discretization.nedelec_trace_degree",
        "integer",
        "order",
        ("3d",),
        "接口 trace 阶次",
        "nedelec_trace_degree",
        "6",
        constraints=(">= 1; must be supplied with interior degree",),
    ),
    _f(
        "discretization.nedelec_interior_degree",
        "integer",
        "order",
        ("3d",),
        "cell interior 阶次",
        "nedelec_interior_degree",
        "6",
        constraints=(">= 1; must be supplied with trace degree",),
    ),
    _f(
        "discretization.visualization_degree",
        "integer",
        "order",
        _ANY_2D_3D,
        "可视化/导出阶次",
        "visualization_degree",
        "6",
        default="2",
        constraints=(">= 1",),
    ),
    _f(
        "discretization.mesh_target_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "目标网格尺寸",
        "mesh_target_size",
        "10.0",
        required=True,
        constraints=("> 0",),
    ),
    _f(
        "discretization.mesh_cell_type",
        "enum",
        "none",
        _ANY_2D_3D,
        "网格单元类型",
        "2D mesh_cell_shape / 3D mesh_cell_type",
        '"hexahedron"',
        required=True,
        allowed=("auto", "triangle", "quadrilateral", "tetrahedron", "hexahedron"),
        constraints=(
            "2D allows triangle/quadrilateral; 3D allows auto/tetrahedron/hexahedron",
        ),
    ),
    _f(
        "discretization.mesh_spacing_mode",
        "enum",
        "none",
        ("3d",),
        "三维网格尺寸分配策略",
        "mesh_spacing_mode",
        '"boundary_fitted"',
        default="auto",
        allowed=("auto", "uniform_strict", "boundary_fitted", "local_refined"),
    ),
    _f(
        "discretization.mesh_refined_size_nm",
        "float",
        "nm",
        ("3d",),
        "三维局部细化尺寸",
        "mesh_refined_size",
        "5.0",
        constraints=("> 0 when refinement is enabled",),
    ),
    _f(
        "discretization.mesh_refinement_radius_nm",
        "float",
        "nm",
        ("3d",),
        "三维局部细化半径",
        "mesh_refinement_radius",
        "25.0",
        constraints=("> 0 when refinement is enabled",),
    ),
    _f(
        "discretization.lock_near_field_template",
        "boolean",
        "none",
        ("2d",),
        "是否锁定二维近场采样模板",
        "mesh_lock_near_field_template",
        "true",
        required=True,
    ),
    _f(
        "discretization.near_field_margin_x_nm",
        "float",
        "nm",
        ("2d",),
        "二维近场 x 向外扩边",
        "near_field_margin_x",
        "5.0",
        required=True,
        constraints=(">= 0",),
    ),
    _f(
        "discretization.near_field_air_top_nm",
        "float",
        "nm",
        ("2d",),
        "二维近场空气侧上边界",
        "near_field_air_top",
        "20.0",
        required=True,
        constraints=("> 0",),
    ),
    _f(
        "discretization.near_field_sub_depth_nm",
        "float",
        "nm",
        ("2d",),
        "二维近场基底侧深度",
        "near_field_sub_depth",
        "10.0",
        required=True,
        constraints=("> 0",),
    ),
    _f(
        "discretization.assembly_backend",
        "enum",
        "none",
        ("3d",),
        "矩阵装配后端",
        "stage4_full3d_assembly_backend",
        '"assembly_time_static_condensed"',
        default="standard_full",
        allowed=(
            "standard_full",
            "assembly_time_static_condensed",
        ),
        constraints=(
            "assembly_time_variable_p_condensed remains internal/research-only "
            "because its geometry-bound degree plan is not a v1 input",
        ),
    ),
    _f(
        "discretization.floquet_constraint_mode",
        "enum",
        "none",
        ("3d",),
        "Floquet 约束模式",
        "floquet_constraint_mode",
        '"auto"',
        default="auto",
        allowed=(
            "auto",
            "topological_edges",
            "sparse_facet",
            "topological_trace_p2",
        ),
    ),
    # boundary
    _f(
        "boundary.use_floquet_x",
        "boolean",
        "none",
        _ANY_2D_3D,
        "是否施加 x 周期约束",
        "2D periodic constraint contract / 3D use_floquet_xy",
        "true",
        default="false",
        constraints=("2D requires true; 3D may disable",),
    ),
    _f(
        "boundary.use_floquet_y",
        "boolean",
        "none",
        ("3d",),
        "是否施加 y 周期约束",
        "use_floquet_xy",
        "true",
        default="false",
        constraints=("3D y component; x/y values must agree",),
    ),
    _f(
        "boundary.vertical_boundary",
        "enum",
        "none",
        _ANY_2D_3D,
        "上下边界模型",
        "stage4_boundary_model / port_boundary_model",
        '"dtn_port"',
        required=True,
        allowed=(
            "dtn_port",
            "pml",
            "robin0",
            "strong_dirichlet",
            "dtn",
            "robin",
        ),
        constraints=(
            "3D uses dtn_port/pml/robin0/strong_dirichlet; airbox maps to "
            "stage1_airbox/floquet_airbox/pml_airbox by Floquet/PML, Fresnel uses "
            "pml, Stage4 uses dtn_port/pml/robin0; 2d_port uses dtn/robin; "
            "2d_scattered uses pml; layered is scattering_background, not a "
            "vertical boundary",
        ),
    ),
    _f(
        "boundary.scattering_background",
        "enum",
        "none",
        _ANY_2D_3D,
        "散射背景的介质层模型",
        "scattering_background",
        '"layered"',
        allowed=("air", "layered"),
        constraints=(
            "required for 2d_scattered and Stage4 3D; Stage4 currently requires "
            "layered; may be omitted for port-only methods",
        ),
    ),
    _f(
        "boundary.dtn_order_policy",
        "enum",
        "none",
        _ANY_2D_3D,
        "DtN 阶次选择策略",
        "stage4_dtn_order_policy",
        '"auto_propagating"',
        allowed=("zero_order", "auto_propagating"),
        constraints=(
            "required only when vertical_boundary is dtn or dtn_port; 2D port maps "
            "to port_use_diffraction_orders; explicit 2D port accepts zero_order "
            "or auto_propagating; TE with a 2D dtn boundary currently accepts only "
            "zero_order; legacy manual order selection is internal because it mixed "
            "output fields into PDE selection",
        ),
    ),
    _f(
        "boundary.dtn_assembly",
        "enum",
        "none",
        _ANY_2D_3D,
        "DtN 装配方式",
        "stage4_dtn_assembly / port_dtn_assembly",
        '"auxiliary"',
        allowed=("auxiliary", "explicit"),
        constraints=("required only when vertical_boundary is dtn or dtn_port",),
    ),
    _f(
        "boundary.use_pml",
        "boolean",
        "none",
        _ANY_2D_3D,
        "是否使用 PML",
        "2D scattered use_pml / 2D port port_use_pml / 3D use_pml",
        "false",
        default="false",
        constraints=("compatible with vertical_boundary",),
    ),
    _f(
        "boundary.pml_top_thickness_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "顶部 PML 厚度",
        "pml_top_thickness",
        "25.0",
        constraints=(">= 0; required when use_pml",),
    ),
    _f(
        "boundary.pml_bottom_thickness_nm",
        "float",
        "nm",
        _ANY_2D_3D,
        "底部 PML 厚度",
        "pml_bottom_thickness",
        "25.0",
        constraints=(">= 0; required when use_pml",),
    ),
    _f(
        "boundary.pml_alpha",
        "float",
        "dimensionless",
        _ANY_2D_3D,
        "PML 吸收强度",
        "pml_alpha",
        "5.0",
        default="5.0",
        constraints=("> 0 when use_pml",),
    ),
    # method
    _f(
        "method.kind",
        "enum",
        "none",
        _ANY_2D_3D,
        "求解方法",
        "method.kind / runner dispatch",
        '"hybrid_iterative"',
        required=True,
        allowed=METHOD_KINDS,
        constraints=(
            "2D uses exactly one of 2d_scattered or 2d_port; 3D uses "
            "full3d_direct/full3d_iterative/hybrid_direct/hybrid_iterative; "
            "no both/all mode",
        ),
    ),
    _f(
        "method.constraint_backend",
        "enum",
        "none",
        ("2d",),
        "二维约束后端",
        "constraint_backend",
        '"mpc_official"',
        required=True,
        allowed=("mpc_official", "manual", "mpc_auto"),
        constraints=("one backend only; no both/all compatibility mode",),
    ),
    _f(
        "method.bottom_interface_nm",
        "float",
        "nm",
        _HYBRID_METHODS,
        "Hybrid 底部接口位置",
        "bottom_interface_nm",
        "10.0",
        required=True,
        constraints=("required for Hybrid; < top_interface_nm",),
    ),
    _f(
        "method.top_interface_nm",
        "float",
        "nm",
        _HYBRID_METHODS,
        "Hybrid 顶部接口位置",
        "top_interface_nm",
        "110.0",
        required=True,
        constraints=("required for Hybrid; > bottom_interface_nm",),
    ),
    _f(
        "method.requested_modes_per_direction",
        "integer",
        "modes/direction",
        _HYBRID_METHODS,
        "用户请求的每方向模态数",
        "requested_modes",
        "120",
        required=True,
        constraints=("required for Hybrid; candidate pool is derived",),
    ),
    _f(
        "method.propagation_model",
        "enum",
        "none",
        _HYBRID_METHODS,
        "Hybrid 内部传播模型",
        "internal_propagation_model",
        '"full3d_uniform_cg"',
        required=True,
        allowed=("continuous_beta", "full3d_uniform_cg"),
    ),
    _f(
        "method.traction_model",
        "enum",
        "none",
        _HYBRID_METHODS,
        "Hybrid 接口 traction 模型",
        "internal_traction_model",
        '"full3d_one_cell_exact_schur"',
        required=True,
        allowed=(
            "continuous_qep_beta",
            "scalar_cg_discrete_derivative",
            "full3d_one_cell_exact_schur",
        ),
    ),
    # solver
    _f(
        "solver.direct_solver_profile",
        "enum",
        "none",
        ("full3d_direct", "hybrid_direct"),
        "有限 direct solver profile",
        "petsc_direct_solver_profile",
        '"default"',
        required=True,
        allowed=("default", "mumps_ooc", "mumps_blr"),
    ),
    _f(
        "solver.linear_solver",
        "enum",
        "none",
        _ALL_METHODS,
        "线性求解器类型",
        "linear_solver",
        '"fgmres"',
        required=True,
        allowed=("direct", "fgmres", "iterative"),
        constraints=(
            "direct methods require direct; hybrid_iterative requires fgmres; "
            "full3d_iterative requires iterative",
        ),
    ),
    _f(
        "solver.ksp_type",
        "enum",
        "none",
        ("full3d_iterative",),
        "Full3D 迭代求解器类型",
        "ksp_type",
        '"fgmres"',
        required=True,
        allowed=("fgmres",),
        constraints=("full3d_iterative fixed profile only",),
    ),
    _f(
        "solver.preconditioner",
        "enum",
        "none",
        ("full3d_iterative", "hybrid_iterative"),
        "公开 preconditioner identity",
        "preconditioner",
        '"hybrid_block_ldu_ilu0_dtn_woodbury"',
        required=True,
        allowed=("full3d_scalable_v1", "hybrid_block_ldu_ilu0_dtn_woodbury"),
        constraints=("only reviewed iterative identities are public",),
    ),
    _f(
        "solver.restart",
        "integer",
        "iterations",
        ("full3d_iterative", "hybrid_iterative"),
        "GMRES/FGMRES restart 长度",
        "restart",
        "90",
        required=True,
        constraints=("only iterative methods; > 0",),
    ),
    _f(
        "solver.max_iterations",
        "integer",
        "iterations",
        ("full3d_iterative", "hybrid_iterative"),
        "最大迭代步数",
        "max_it",
        "4500",
        required=True,
        constraints=("only iterative methods; > 0",),
    ),
    _f(
        "solver.relative_tolerance",
        "float",
        "relative residual",
        ("hybrid_iterative",),
        "相对残差容差",
        "rtol",
        "5.0e-9",
        required=True,
        constraints=("only hybrid_iterative; > 0 and finite",),
    ),
    _f(
        "solver.absolute_tolerance",
        "float",
        "absolute residual",
        ("hybrid_iterative",),
        "绝对残差容差",
        "atol",
        "0.0",
        required=True,
        constraints=("only hybrid_iterative; >= 0 and finite",),
    ),
    _f(
        "solver.initial_guess",
        "enum",
        "none",
        ("hybrid_iterative",),
        "初始向量策略",
        "initial_guess",
        '"zero"',
        required=True,
        allowed=("zero",),
    ),
    _f(
        "solver.ilu_level",
        "integer",
        "level",
        ("hybrid_iterative",),
        "ILU fill level",
        "ilu_level",
        "0",
        required=True,
        constraints=(">= 0",),
    ),
    _f(
        "solver.ilu_shift",
        "float",
        "dimensionless",
        ("hybrid_iterative",),
        "ILU diagonal shift",
        "ilu_shift",
        "0.1",
        required=True,
        constraints=("finite",),
    ),
    _f(
        "solver.subdomain_count_per_endcap",
        "integer",
        "subdomains/endcap",
        ("hybrid_iterative",),
        "每个 endcap 的子域数",
        "subdomain_count_per_endcap",
        "1",
        required=True,
        constraints=(">= 1",),
    ),
    _f(
        "solver.overlap_fraction",
        "float",
        "fraction",
        ("hybrid_iterative",),
        "子域重叠比例",
        "overlap_fraction",
        "0.0",
        required=True,
        constraints=("0 <= value < 1",),
    ),
    _f(
        "solver.side_residual_correction_steps",
        "integer",
        "steps",
        ("hybrid_iterative",),
        "固定侧向残差修正次数",
        "side_residual_correction_steps",
        "2",
        required=True,
        allowed=("1", "2"),
        constraints=("only hybrid_iterative; no fallback",),
    ),
    # execution
    _f(
        "execution.mpi_size",
        "integer",
        "MPI ranks",
        _ANY_2D_3D,
        "外层 launcher 使用的 MPI 数",
        "execution.mpi_size / MPI.COMM_WORLD.size check",
        "8",
        required=True,
        constraints=(">= 1; worker size must match",),
    ),
    _f(
        "execution.warning_memory_gib",
        "float",
        "GiB",
        _ANY_2D_3D,
        "用户资源警告线",
        "watchdog warning threshold",
        "10.0",
        required=True,
        constraints=("> 0; generic policy, not authority hard gate",),
    ),
    _f(
        "execution.terminate_memory_gib",
        "float",
        "GiB",
        _ANY_2D_3D,
        "用户资源终止线",
        "watchdog terminate threshold",
        "14.0",
        required=True,
        constraints=("> warning_memory_gib",),
    ),
    _f(
        "execution.timeout_seconds",
        "integer",
        "seconds",
        _ANY_2D_3D,
        "单次运行时间上限",
        "watchdog timeout",
        "7200",
        required=True,
        constraints=("> 0; generic policy, not authority hard gate",),
    ),
    _f(
        "execution.memory_limit_gb",
        "float",
        "GiB",
        ("3d",),
        "Full3D 运行内存上限",
        "memory_limit_gb",
        "2.0",
        constraints=("> 0; required for full3d_iterative",),
    ),
    _f(
        "execution.require_zero_swap",
        "boolean",
        "none",
        _ANY_2D_3D,
        "是否要求 swap 为零",
        "swap policy",
        "true",
        required=True,
    ),
    # output
    _f(
        "output.results_root",
        "path",
        "filesystem path",
        _ANY_2D_3D,
        "结果根目录",
        "results_root",
        '"results"',
        required=True,
        constraints=("must not overwrite an existing run",),
    ),
    _f(
        "output.unique_output",
        "boolean",
        "none",
        _ANY_2D_3D,
        "是否创建唯一结果目录",
        "unique_output",
        "true",
        default="true",
    ),
    _f(
        "output.export_fields",
        "boolean",
        "none",
        _ANY_2D_3D,
        "导出场字段",
        "field export policy",
        "true",
        default="false",
    ),
    _f(
        "output.export_diffraction_orders",
        "boolean",
        "none",
        _ANY_2D_3D,
        "导出衍射级",
        "diffraction output policy",
        "true",
        default="true",
    ),
    _f(
        "output.compute_power_metrics",
        "boolean",
        "none",
        ("2d",),
        "是否计算二维功率指标",
        "compute_power_metrics",
        "true",
        required=True,
    ),
    _f(
        "output.power_probe_num_points",
        "integer",
        "points",
        ("2d",),
        "二维功率探针采样点数",
        "power_probe_num_points",
        "1001",
        required=True,
        constraints=("> 1",),
    ),
    _f(
        "output.generate_png_plots",
        "boolean",
        "none",
        ("2d",),
        "是否生成二维 PNG 图",
        "generate_png_plots",
        "false",
        required=True,
    ),
    _f(
        "output.export_canonical_vectors",
        "boolean",
        "none",
        ("3d",),
        "导出 canonical 向量",
        "canonical field export policy",
        "true",
        default="false",
    ),
    _f(
        "output.export_modal_amplitudes",
        "boolean",
        "none",
        ("3d",),
        "导出 modal amplitude",
        "modal export policy",
        "true",
        default="false",
    ),
    _f(
        "output.export_reference_planes",
        "boolean",
        "none",
        ("3d",),
        "导出 reference planes",
        "reference plane export policy",
        "true",
        default="false",
    ),
    _f(
        "output.reference_plane_z_nm",
        "float_array",
        "nm",
        ("3d",),
        "reference plane 的 z 坐标",
        "full3d_reference_plane_z",
        "[10.0, 30.0, 60.0, 90.0, 110.0]",
        constraints=("required when export_reference_planes",),
    ),
    _f(
        "output.diffraction_sample_count_x",
        "integer",
        "samples",
        ("3d",),
        "衍射级提取的 x 采样数（不同于 reference plane 采样）",
        "diffraction_sample_count_x",
        "24",
        default="24",
        constraints=("> 0",),
    ),
    _f(
        "output.diffraction_sample_count_y",
        "integer",
        "samples",
        ("3d",),
        "衍射级提取的 y 采样数（不同于 reference plane 采样）",
        "diffraction_sample_count_y",
        "24",
        default="24",
        constraints=("> 0",),
    ),
    _f(
        "output.top_probe_z_nm",
        "float",
        "nm",
        ("3d",),
        "顶部衍射探针 z 坐标",
        "diffraction_top_probe_z",
        "110.0",
        constraints=("optional explicit override",),
    ),
    _f(
        "output.bottom_probe_z_nm",
        "float",
        "nm",
        ("3d",),
        "底部衍射探针 z 坐标",
        "diffraction_bottom_probe_z",
        "10.0",
        constraints=("optional explicit override",),
    ),
    _f(
        "output.probe_fraction",
        "float",
        "fraction",
        ("3d",),
        "探针在相邻区域中的归一化位置",
        "diffraction_probe_fraction",
        "0.75",
        default="0.75",
        constraints=("0 < value < 1; optional when explicit probes are set",),
    ),
    _f(
        "output.sample_count_x",
        "integer",
        "samples",
        ("3d",),
        "reference plane x 采样数",
        "full3d_reference_sample_count_x",
        "40",
        default="40",
        constraints=("> 0; required when export_reference_planes",),
    ),
    _f(
        "output.sample_count_y",
        "integer",
        "samples",
        ("3d",),
        "reference plane y 采样数",
        "full3d_reference_sample_count_y",
        "20",
        default="20",
        constraints=("> 0; required when export_reference_planes",),
    ),
    _f(
        "output.diffraction_order_max_m",
        "integer",
        "order",
        _ANY_2D_3D,
        "最大 x 衍射级",
        "2D diffraction_order_count / 3D diffraction_order_max_m (postprocess reporting only; never PDE DtN selection)",
        "2",
        constraints=(">= 0; required when export_diffraction_orders",),
    ),
    _f(
        "output.diffraction_order_max_n",
        "integer",
        "order",
        ("3d",),
        "最大 y 衍射级",
        "diffraction_order_max_n",
        "2",
        constraints=(">= 0; required when export_diffraction_orders",),
    ),
)

PUBLIC_FIELD_SPECS: Final = IDENTITY_FIELD_SPECS + FIELD_SPECS
PUBLIC_FIELD_KEYS: Final = tuple(spec.key for spec in PUBLIC_FIELD_SPECS)
FIELD_SPECS_BY_KEY: Final = MappingProxyType(
    {spec.key: spec for spec in PUBLIC_FIELD_SPECS}
)
SECTION_FIELD_KEYS: Final = MappingProxyType(
    {
        section: tuple(
            spec.key for spec in FIELD_SPECS if spec.key.startswith(f"{section}.")
        )
        for section in SECTION_NAMES
    }
)

__all__ = [
    "FIELD_SPECS",
    "FIELD_SPECS_BY_KEY",
    "FieldSpec",
    "IDENTITY_KEYS",
    "IDENTITY_FIELD_SPECS",
    "METHOD_KINDS",
    "PUBLIC_FIELD_SPECS",
    "PUBLIC_FIELD_KEYS",
    "SCHEMA_VERSION",
    "SECTION_FIELD_KEYS",
    "SECTION_NAMES",
]
